name = "NOYAL MARTIN"
description = "Computer Science Engineer."
keywords = "python, html,css, javascript and the cliche goes on ......"
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"

[[sections]]
title = "Projects"
description = "Here are some of my projects"
[[sections.items]]
title = "Project1"
description = "Just starting... partially developed for Hackathon "
url = "https://github.com/DevVoyagerX/Decepticodes/tree/main"
[[sections.items]]
title = "Just something"
description = "......"
url = "google.com"
[[sections.items]]
title = "COMING SOON"
description = "maybe will be updated later or never."
url = "https://thatsthefinger.com/"

[[sections]]
title = "Links"
description = "Look for me on these websites"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/n0yal_/"
[[sections.items]]
title = "Linkedin"
url = "https://www.linkedin.com/in/noyal-martin-3301n/"
